# General artefact name, as this is only the C library, the conda package is suffixed with "-c"
{% set name = "zookeeper" %}
{% set version = "3.4.11" %}
{% set sha256 = "f6bd68a1c8f7c13ea4c2c99f13082d0d71ac464ffaf3bf7a365879ab6ad10e84" %}

package:
  name: {{ name|lower }}-c
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://archive.apache.org/dist/{{ name }}/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - toolchain
    - autoconf
    - automake

test:
  commands:
    - test -f $PREFIX/lib/libzookeeper_mt.a
    - test -f $PREFIX/lib/libzookeeper_st.a
    - test -f $PREFIX/lib/libzookeeper_mt.2.dylib  # [osx]
    - test -f $PREFIX/lib/libzookeeper_mt.dylib  # [osx]
    - test -f $PREFIX/lib/libzookeeper_st.2.dylib  # [osx]
    - test -f $PREFIX/lib/libzookeeper_st.dylib  # [osx]
    - test -f $PREFIX/lib/libzookeeper_mt.so.2  # [linux]
    - test -f $PREFIX/lib/libzookeeper_mt.so  # [linux]
    - test -f $PREFIX/lib/libzookeeper_st.so.2  # [linux]
    - test -f $PREFIX/lib/libzookeeper_st.so  # [linux]

about:
  home: http://zookeeper.apache.org/
  license: Apache 2.0
  summary: 'ZooKeeper is a centralized service for maintaining configuration information, naming, providing distributed synchronization, and providing group services.'

extra:
  recipe-maintainers:
    - xhochy
