# General artefact name, as this is only the C library, the conda package is suffixed with "-c"
{% set name = "zookeeper" %}
{% set version = "3.4.13" %}
{% set sha256 = "7ced798e41d2027784b8fd55c908605ad5bd94a742d5dab2506be8f94770594d" %}

package:
  name: {{ name|lower }}-c
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://archive.apache.org/dist/{{ name }}/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True  # [win]

requirements:
  build:
    - autoconf
    - automake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

test:
  commands:
    - test -f $PREFIX/lib/libzookeeper_mt.a
    - test -f $PREFIX/lib/libzookeeper_st.a
    - test -f $PREFIX/lib/libzookeeper_mt.2.dylib  # [osx]
    - test -f $PREFIX/lib/libzookeeper_mt.dylib  # [osx]
    - test -f $PREFIX/lib/libzookeeper_st.2.dylib  # [osx]
    - test -f $PREFIX/lib/libzookeeper_st.dylib  # [osx]
    - test -f $PREFIX/lib/libzookeeper_mt.so.2  # [linux]
    - test -f $PREFIX/lib/libzookeeper_mt.so  # [linux]
    - test -f $PREFIX/lib/libzookeeper_st.so.2  # [linux]
    - test -f $PREFIX/lib/libzookeeper_st.so  # [linux]

about:
  home: http://zookeeper.apache.org/
  license: Apache 2.0
  summary: 'ZooKeeper is a centralized service for maintaining configuration information, naming, providing distributed synchronization, and providing group services.'

extra:
  recipe-maintainers:
    - xhochy
