travis:
  secure:
    BINSTAR_TOKEN: KZsRvJe2WnSefSrO4sP+tizOH1hMdRkKiYa+Id2d8dxyKQCF4dnz7px35HwD54OjszTTUob3gTlVDYhWYD7YoCSD+4/aU80GtAQSMK4GGFIZTuiAHve/mwwU0ZzDZ8MPJIfeiq6DJicHnPb2q398lZYwImaZ/p10Kl9AoZ936WqLg4RTg6Ijs0eoRGOdjO6jTtg46bVRTwStIacvxgzTnjEpp99xXFCwEsYKIj59netIdRTVaDvXA/o3rMKs7RTw+bvnWK1X3sSaK6VhAJx5/UOqZCpb5ZpJuP+I0uQrxJqZiKsWDdXQxgOesdoN05JDx19E2t0JbAz3s38raGhBgNrIfyOeaz4yoxtlKAEOCGMs1CviM2aK6W9t6ixrWErGqdfa4wGBwXdLS8MuP9P7N+VT/pJz25Yee/Mj1z2ouCJ7mZWWR9gwWsmtDzrGJI/T38MK79xf7fazIbvaYfdzb083g8bKli2xN7/34n7cvTf/oeu8quni3sT8YTW3+0lMt4U8SKVxFM4aA2+gcSec585N0qxNjKQr71wbgZ5vdzX72SkoaAKO/pLj8aEiK350ODu1LpUH41Dw0uUE4n4bTFlqz7Eg8eVsWLWoUgzd7w9Ijx2FRODlgUos7ZegZwxbWC5t1mOVwbm2CEZn0sa4KewABsZ1JZG/pdU/efeup2s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
