travis:
  secure:
    BINSTAR_TOKEN: Vf2FQrfQqXuIwgsEEAeU1wPoVPFlvSlKqUmWED8pbumJyqdE9PWIqgeJHKm+Ew5cBkrqhcggRZPJqlXUf+Ft8Ki9vGrSVxksZ2bKR/PWFSfDCtxXVAnP+KFu7zdZSPps5Bfp4RZ7d3aUpnhDww021lzzhyIppQkYrHLPceJGUKTtx9BNw5ta6dkDucxa+LE22JWgyT+qDt1QAxa19sJ8QX/2AcTG/bDr/gL4qJHE0A7fqkot/aAyPXXad4XD6J5fYks+Niab3JMtjuWwOxUUKgZNhxC4jtn6af+1uZW0+gdq+L3l6YCw/Y/2dyEMNvrViWmwTWxD0LYKTgfCVzgx1FhCW+bJSio54l1EDTyhEWqyZIJDYTv/S447WEQnesEUs5BCexPdRwYqAwUwSFvvB0ohvaNUDalAZYQB7PIS6uhgIqd2HJ439EPRWJsfltRBZXSUuxHlMpJLo8oAf9bsV/krp25Qb//04CqqC4KIXzin39x6ppbx+7guCaTDwG09Xl6xrffdXiP6IprtfKB3mLfnJ+5sNn88uyrkUQ0c6OI/fItR6MHwDZcpgp44avieqD8cvDMWx8HDYT06YcWJrCGUppXWcLQn6aM6Fir6x+7njgdvrt9sOyDLUK4CUVF3Fu2A/DOSN55+KgaQKSHCRSTw9u2T0omswr9Z4RcpN94=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
