travis:
  secure:
    BINSTAR_TOKEN: VfhnrmLX5Z2y+0JglGPIlTYiuz9OB76E8KhRKTILonH9x6FhX064CMpWMo2gqPt+5Lymi7N4Vgh3y7Tg2bIF4pG+gtd6ATNfJOKqlXk1Uotx+dukOKiPba/nYU8lBXqHEBnwdQP46FzdrIMdzVLvFBWDRL2axMguNOysAcDhZeNX3zEo9vgUvPOcp8x+aF5Llnd7WPGPX950cjhsN5C2eI9sIi7ypywhOsWQUB+15USa0vwMnQxy9hNIewTzMaQlTI0ZYVXLTF8zxvZRj/Fseg218tUtyOudSgQaB4CEgoYnZRMrWdBz1q1jIR17h4t46OOBdB49zERXqQF2D8nYtiGFQ2K5TRNc9rw5Al3MCHMtOiuIHS606oA+kJUH9mpq2y6Rk+W1nfTEO2E+Nlnnk/DqXc2F5lCvjpMVENpeG6J4xVw/jhJc3++1QJQoOQnFX8tCoiexaimBE0Gz/ERAUFoBfktaDieznn8n4SdNPxshzr8Kw5vTg0HN5puIjQdCJt9tvZ8Dh+6o4FMI2CF/VVp6LzRudRxb61JBbWIqccfDLCl9o8QfIPwrB1JdrYzyy4NDvBdlK539XfxxdqISwu0XHKfWd3Kt+2Vv/HvUeTsMYctVwjZqrsqbv4yo8y3FROrAqyXMml4068yt7FshA/ohNsI4i2OBfO61U3XrRgY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
